// <auto-generated />
using System;
using FluxoCaixa.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluxoCaixa.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250322122520_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FluxoCaixa.Domain.Entities.Consolidation", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_credit");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_dedit");

                    b.HasKey("Date");

                    b.ToTable("consolidations", (string)null);
                });

            modelBuilder.Entity("FluxoCaixa.Domain.Entities.Launch", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.HasKey("Date", "Type");

                    b.ToTable("launches", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
